version: '3'

services:
  nginx-docker-app:
    container_name: nginx-docker-app
    image: "tlqkrus012345/nginx-docker-test"
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nginx-docker-app